backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: true
  repo: brob/plug11ty.com # Path to your GitHub repository

publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "categories"
    label: "Categories"
    folder: "categories"
    fields: 
      - { label: "Category Name", name: "category", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "plugins"
    label: "Plugins"
    folder: "plugins"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "/plugin.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Categories"
        name: "categories" 
        widget: "relation"
        collection: "categories"
        searchFields: ["name"]
        valueField: "name"
        required: false     
      - label: "Maintainer Info"
        name: "maintainer" 
        widget: "object" 
        required: false
        fields: 
          - label: "Maintainer Name"
            name: "name"
            widget: "string"
            required: false
          - label: "Maintainer URL"
            name: "url"
            widget: "string"
            required: false
      
      - { label: "GitHub/NPM URL", name: "githubUrl", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}